# Use a minimal base image
FROM python:3.11-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copy app code
COPY . .
EXPOSE 5000
# Use gunicorn for production
CMD ["gunicorn", "wsgi:app", "--bind", "0.0.0.0:5000", "--workers", "4"]
# CMD ["flask","--app","backend","run"]